---
# tasks file for ansible-icinga2

- name: install package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - icinga2
    - icinga2-common
    - vim
    - php5
    - php5-intl
    - php5-imagick
    - php5-pgsql
- include: vim.yml
- include: pgsql.yml
- include: web.yml tags=web
