- name: install postgresql
  apt: name={{ item }} state=present
  with_items:
    - python-psycopg2
    - postgresql
    - icinga2-ido-pgsql

- name: backup actual pg_hba.conf
  fetch: src={{ icinga2_db_postgresql_pg_hba_conf_path }} dest=/tmp/{{ ansible_hostname }}-pg_hba.conf flat=yes

- name: temporary change pg_hba.conf
  copy: src=pg_hba.conf dest={{ icinga2_db_postgresql_pg_hba_conf_path }} owner=postgres group=postgres mode=640
  notify: restart postgres

- name: create postgre DB
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ icinga2_db_name }} encoding='UTF-8'

- name: create postgres user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ icinga2_db_user_name }} password={{ icinga2_db_user_passwd }}

- name: restore pg_hba.conf
  copy: src=/tmp/{{ ansible_hostname }}-pg_hba.conf dest={{ icinga2_db_postgresql_pg_hba_conf_path }} owner=postgres group=postgres mode=640

- name: add icinga2 user access to pg_hba.conf
  lineinfile: dest={{ icinga2_db_postgresql_pg_hba_conf_path }} line="local {{ icinga2_db_name }} {{ icinga2_db_user_name }} md5"

- lineinfile: dest={{ icinga2_db_postgresql_pg_hba_conf_path }} line="host  {{ icinga2_db_name }} {{ icinga2_db_user_name }} 127.0.0.1/32 md5"

- lineinfile: dest={{ icinga2_db_postgresql_pg_hba_conf_path }} line="host  {{ icinga2_db_name }} {{ icinga2_db_user_name }} ::1/128 md5"
  notify: restart postgres

- name: enable ido-pgsql feature
  file: src=/etc/icinga2/features-available/ido-pgsql.conf dest=/etc/icinga2/features-enabled/ido-pgsql.conf owner=root group=root state=link
  notify: restart icinga2
