- name: install postgresql
  apt: name={{ item }} state=present
  with_items:
    - python-psycopg2
    - postgresql-9.4
    - postgresql-common
    - postgresql-client
    - icinga2-ido-pgsql

- name: create postgre DB
  become: yes
  become_user: postgres
  postgresql_db: name={{ icinga2_db_name }} encoding='UTF-8'

- name: create postgres user
  become: yes
  become_user: postgres
  postgresql_user: name={{ icinga2_db_user_name }} password={{ icinga2_db_user_passwd }}

- name: add icinga2 user access to pg_hba.conf
  lineinfile: dest={{ icinga2_db_postgresql_pg_hba_conf_path }} line="local {{ icinga2_db_name }} {{ icinga2_db_user_name }} md5"

- lineinfile: dest={{ icinga2_db_postgresql_pg_hba_conf_path }} line="host  {{ icinga2_db_name }} {{ icinga2_db_user_name }} 127.0.0.1/32 md5"

- lineinfile: dest={{ icinga2_db_postgresql_pg_hba_conf_path }} line="host  {{ icinga2_db_name }} {{ icinga2_db_user_name }} ::1/128 md5"
  notify: restart postgres

- name: enable ido-pgsql feature
  file: src=/etc/icinga2/features-available/ido-pgsql.conf dest=/etc/icinga2/features-enabled/ido-pgsql.conf owner=root group=root state=link
  notify: restart icinga2

- name: does the ido pgsql db schema exist ?
  become: yes
  become_user: postgres
  shell: psql -d {{ icinga2_db_name }} -c "\d"
  register: result

- name: import ido pgsql db schema
  become: yes
  become_user: postgres
  shell: psql -d {{ icinga2_db_name }} < /usr/share/icinga2-ido-pgsql/schema/pgsql.sql
  when: "'No relations' in result.stdout or 'Aucune relation' in result.stdout"
  register: result
  notify: restart icinga2

- name: set postgresql privileges for ido pgsql user
  become: yes
  become_user: postgres
  postgresql_privs: db={{ icinga2_db_name }} privs=ALL roles={{ icinga2_db_user_name }} type=database

- name: set postgresql privileges for ido pgsql user
  become: yes
  become_user: postgres
  postgresql_privs: db={{ icinga2_db_name }} privs=USAGE,SELECT roles={{ icinga2_db_user_name }} type=sequence objs=ALL_IN_SCHEMA

- name: set postgresql privileges for ido pgsql user
  become: yes
  become_user: postgres
  postgresql_privs: db={{ icinga2_db_name }} privs=INSERT,SELECT,UPDATE,DELETE roles={{ icinga2_db_user_name }} type=table objs=ALL_IN_SCHEMA

- name: ido configuration file
  template: src=etc/icinga2/{{ item }} dest=/etc/icinga2/{{ item }} owner=nagios group=nagios
  with_items:
    - features-available/ido-pgsql.conf
  notify: restart icinga2
