---
# handlers file for ansible-icinga2

- name: stop postgres
  service: name=postgresql state=stopped

- name: start postgres
  service: name=postgresql state=started

- name: restart postgres
  service: name=postgresql state=restarted

- name: restart icinga2
  service: name=icinga2 state=restarted

- name: restart apache2
  service: name=apache2 state=restarted
